# Generated by Django 4.2.2 on 2023-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
